---

- name: Set hostname
  hostname: name={{ inventory_hostname_short }}
  sudo: true
  tags:
    - configuration
    - hosts

- name: Update /etc/hosts local fqdn
  lineinfile: "dest=/etc/hosts
              regexp='^127\\.0\\.1\\.1'
              line='127.0.1.1\t{{ inventory_hostname }}  {{ inventory_hostname_short }}'
              state=present
              backup=yes"
  sudo: true
  tags: [configuration,hosts]

- name: Display all variables/facts known for a host
  debug: var=inventory_hostname_short

- name: Display all variables/facts known for a host
  debug: var=inventory_hostname

- name: Replace existing hosts entry for FQDN
  lineinfile:
             dest: /etc/hosts
             regexp: "^{{ ansible_ssh_host }}(.*)"
             line: "{{ ansible_ssh_host }}\t{{ inventory_hostname }} {{ inventory_hostname_short }}"
             state: present
             backrefs: true
             backup: yes
  sudo: true
  tags: [configuration,hosts,orighost]

# These may be set by the Providor - change only if you need to
- name: Update nameservers in the resolv.conf
  template:
       src: "resolve.conf.j2"
       dest: /etc/resolv.conf
       backup: yes
       owner: root
       group: root
       mode: 755
  when: nameserver_update is defined and nameserver_update == True
# when: inventory_hostname in groups['local']

# TODO check this see https://github.com/knopki/ansible-hostname/tree/cc1781882237ef0acaea4f057585c57a4bf32296
#- name: Keep temporary old hostname in /etc/hosts
#  lineinfile:
#    dest=/etc/hosts
#    regexp="^127\.0\.1\.1(.*)"
#    line="127.0.1.1{{'\t'}}{{ hostname_name }}{% if hostname_name != hostname_fqdn %}{{'\t'}}{{ hostname_fqdn }}{% endif %}\1"
#    state=present
#    backup=yes
#    backrefs=yes
#  when: ansible_hostname != hostname_name
#  tags:
#    - configuration
#    - hostname

#- name: Set hostname
#  hostname: name={{ hostname_name }}
#  when: hostname_name is defined
#  tags:
#    - configuration
#    - hostname

#- name: Update /etc/hosts
#  lineinfile:
#    dest=/etc/hosts
#    regexp="^127\.0\.1\.1"
#    line="127.0.1.1{{'\t'}}{{ hostname_name }}{% if hostname_name != hostname_fqdn %}{{'\t'}}{{ hostname_fqdn }}{% endif %}"
#    state=present
#  tags: [configuration,hostname]