---

- name: Set hostname
  hostname:
    name: "{{ inventory_hostname_short }}"
  become: true
  tags: [configuration,hosts]

- name: Update /etc/hosts local fqdn
  lineinfile:
    dest: /etc/hosts
    regexp: '^127\.0\.1\.1'
    line: "127.0.1.1\t{{ inventory_hostname }} {{ inventory_hostname_short }}"
    insertafter: '^127.0.0.1'
    state: present
    backup: yes
    owner: root
    group: root
    mode: 0644
  become: true
  tags: [configuration,hosts]

# we can add host entries for all of the related inventory
# For this to work you need to have gathered facts even if limiting the import_playbook
# see Readme

- block:
  - name: Display all variables/facts known for a host
    debug:
      msg: "{{ hostvars[item]['ansible_facts']['default_ipv4']['address'] }}\t{{hostvars[item]['ansible_facts']['fqdn']}} {{hostvars[item]['ansible_hostname']}}"
      verbosity: 3
    with_items: "{{ groups[f5base_hosts_group] }}"
    when: ansible_hostname != item and item not in groups['local']
    tags: [configuration,hosts]

  - meta: end_play
    when: ansible_verbosity > 2

  - name: Add IP address of all hosts to all hosts
    lineinfile:
      dest: /etc/hosts
      regexp: "^{{ hostvars[item]['ansible_facts']['default_ipv4']['address'] }}"
      line: "{{ hostvars[item]['ansible_facts']['default_ipv4']['address'] }}\t{{hostvars[item]['ansible_facts']['fqdn']}} {{hostvars[item]['ansible_hostname']}}"
      state: present
      insertbefore: '^# IPv6'
    become: yes
    when: ansible_hostname != item and item not in groups['local'] and hostvars[item]['ansible_facts']['default_ipv4']['address'] != ansible_ssh_host
    with_items: "{{ groups[f5base_hosts_group] }}"
  when: hostvars is defined
  tags: [configuration,hosts]

- name: Add the custom inventory into /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: "^{{ item.ip }}\t{{item.name}}"
    line: "{{ item.ip }}\t{{item.name}}"
    state: present
  when: f5base_custom_hosts_entries is defined
  with_items:
    - "{{ f5base_custom_hosts_entries }}"
  tags: [configuration,hosts]

- name: Display all variables/facts known for a host
  debug:
    var: hostvars[inventory_hostname_short]
    verbosity: 4
  tags: [configuration,hosts]

- name: Display all variables/facts known for a host
  debug:
    var: hostvars[inventory_hostname]
    verbosity: 4
  tags: [configuration,hosts]

- name: Replace existing hosts entry for FQDN
  lineinfile:
    dest: /etc/hosts
    regexp: "^{{ ansible_ssh_host }}(.*)"
    line: "{{ ansible_ssh_host }}\t{{ inventory_hostname }} {{ inventory_hostname_short }}"
    state: present
    backrefs: true
    backup: yes
  become: true
  tags: [configuration,hosts,orighost]

- name: Replace existing hosts entry for FQDN
  lineinfile:
    dest: /etc/hosts
    regexp: "^{{ ansible_ipv6 }}(.*)"
    line: "{{ ansible_ipv6 }}\t{{ inventory_hostname }} {{ inventory_hostname_short }}"
    state: present
#    backrefs: true
    backup: yes
  when: ansible_ipv6 is defined
  become: true
  tags: [configuration,hosts,orighost]

# These may be set by the Providor - change only if you need to
- name: Update nameservers in the resolv.conf
  template:
    src: "resolve.conf.j2"
    dest: /etc/resolv.conf
    backup: yes
    owner: root
    group: root
    mode: 755
  when: nameserver_update is defined and nameserver_update == True
  tags: [configuration,hosts]
# when: inventory_hostname in groups['local']
