---

- name: Put up a specific Postrotate file
  template:
     src: "{{ item.file_src }}"
     dest: "{{ item.file_dest }}/{{ item.cmd}}"
     owner: root
     group: root
     mode: 0700
  with_items: f5base_logrotate_actions
  when: item.isfile | bool
  become: true

- name: Update Rsyslog
  template:
    src: logrotate-rsyslog.conf.j2
    dest: /etc/logrotate.d/rsyslog
    backup: yes
  become: true
