---

#
# Essentials
# http://www.howtoforge.com/how-to-configure-automatic-updates-on-debian-wheezy

- import_tasks: packages-debian.yml
  when: ansible_os_family == 'Debian'

- import_tasks: packages-redhat.yml
  when: ansible_os_family == 'RedHat'

- import_tasks: security.yml
  when: f5base_dosecurity|bool

- import_tasks: logrotate.yml
  when: f5base_dologrotate|bool
  tags: [configuration,logrotate]

- import_tasks: host.yml
  when: f5base_dohostname|bool
  tags: [configuration,hosts]

- import_tasks: locale.yml
  when: f5base_dolocale|bool
  tags: [base,locale]

- import_tasks: motd.yml
  when: f5base_domotd|bool

# Disable some services we don't need
- name: Disable Unrequired services
  service:
     name: "{{ item }}"
     state: stopped
     enabled: no
  with_items: "{{ srv_to_stop }}"
  when: inventory_hostname not in groups['local']
  tags: [base, services]
  ignore_errors: true

- import_tasks: gpg.yml
  when: f5base_do_gpg | bool
  tags: [base, gpg]
