---

#
# Essentials
# http://www.howtoforge.com/how-to-configure-automatic-updates-on-debian-wheezy

- include: packages-debian.yml
  when: ansible_os_family == 'Debian'

- include: packages-redhat.yml
  when: ansible_os_family == 'RedHat'

- include: host.yml
  when: f5base_dohostname

- include: motd.yml
  when: f5base_domotd

# Disable some services we don't need
- name: Disable Unrequired services
  service:
     name: "{{ item }}"
     state: stopped
     enabled: no
  with_items: "{{srv_to_stop}}"
  when: inventory_hostname not in groups['local']
  ignore_errors: yes
