---

#
# Essentials
# http://www.howtoforge.com/how-to-configure-automatic-updates-on-debian-wheezy

- import_tasks: packages-debian.yml
  when: ansible_os_family == 'Debian'

- import_tasks: packages-redhat.yml
  when: ansible_os_family == 'RedHat'

- import_tasks: security.yml
  when: f5base_dosecurity


- import_tasks: host.yml
  when: f5base_dohostname

- import_tasks: locale.yml
  when: f5base_dolocale
  tags: [base,locale]

- import_tasks: motd.yml
  when: f5base_domotd

# Disable some services we don't need
- name: Disable Unrequired services
  service:
     name: "{{ item }}"
     state: stopped
     enabled: no
  with_items: "{{srv_to_stop}}"
  when: inventory_hostname not in groups['local']
  tags: [base,services]
  ignore_errors: yes
