---

#
# Essentials
# http://www.howtoforge.com/how-to-configure-automatic-updates-on-debian-wheezy

- include: apt.yml
  when: ansible_os_family == 'Debian'
  
- include: host.yml

- include: motd.yml

# Disable some services we don't need
- name: Disable Unrequired services
  service:
     name: "{{ item }}"
     state: stopped
     enabled: no
  with_items: srv_to_stop 
  when: inventory_hostname not in groups['local']  
  ignore_errors: yes