---

# MOTD
# see http://www.howtogeek.com/104708/how-to-customize-ubuntus-message-of-the-day/
# this simply bypasses the landscape stuff on Ubuntu

- name: Update motd
  template: src=motd.j2 dest=/etc/motd
  become: true
  tags:
     - configuration
     - motd
