---

- name: Install packages | Required packages that may not be installed | RedHat
  yum:
    name: "{{ f5base_packages_required }}"
    state: present
  become: true

- name: Ensure required packages are running and enabled at system start. | RedHat
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  with_items: "{{ f5base_packages_started }}"
  become: true

- name: Install yum-cron.
  yum:
    pkg: yum-cron
    state: present

- name: Ensure yum-cron is running and enabled on boot.
  service:
    name: yum-cron
    state: started
    enabled: true
