---

- name: Install packages | Required packages that may not be installed
  yum:
    name: "{{ item }}"
    state: present
  sudo: true
  with_items: f5base_packages_required

- name: Ensure required packages are running and enabled at system start.
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  sudo: true

- name: Install yum-cron.
  yum: pkg=yum-cron state=installed

- name: Ensure yum-cron is running and enabled on boot.
  service: name=yum-cron state=started enabled=yes