---
# tasks file for sysstat

- name: Install sysstat
  ansible.builtin.package:
    name: "{{ f5base_sysstat.packages }}"
    state: present

- name: Enable sysstat
  ansible.builtin.lineinfile:
    path: /etc/default/sysstat
    regexp: '^ENABLED='
    line: 'ENABLED="true"'
    owner: root
    group: root
    mode: "0644"
  when:
    - ansible_facts['os_family'] == "Debian"
    - f5base_systat_enable_logging

- name: Start and enable sysstat
  ansible.builtin.service:
    name: "{{ f5base_sysstat.service }}"
    state: started
    enabled: true